---

- name: find AMI
  ec2_ami_facts:
    profile: '{{ aws_profile }}'
    # this Ansible module supports automatic role assumption

    filters:  '{{ _aws_ec2_i.image_filters | default(omit) }}'
    image_id: '{{ _aws_ec2_i.image         | default(omit) }}'
    owner:    '{{ _aws_ec2_i.image_owner   | default(omit) }}'

    region: '{{ aws_region }}'
  register: _aws_ec2_ami_facts

- name: set AMI fact
  set_fact:    
    _aws_ec2_ami: >-
      {{
        _aws_ec2_ami_facts.images
        | sort(attribute=(_aws_ec2_i.image_sort_attribute
                          | default("creation_date")),
                 reverse=(_aws_ec2_i.image_sort_reverse
                          | default(True)))
        | first
      }}

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: selected AMI <b>{{ _aws_ec2_ami.image_id }}</b>
  when: notifier_role is defined
