---

- name: find network interface ID
  ec2_eni_facts:
    filters:
      status: available
      'tag:Environment': '{{ _aws_ec2_i["environment"] }}'
      'tag:Name': '{{ _aws_ec2_i["function"] }}'
      vpc-id: '{{ _aws_vpc_id }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_ec2_eni_facts

- name: set network interface ID fact
  set_fact:
    _aws_ec2_eni_id: >-
      {{ _aws_ec2_eni_facts.network_interfaces[0].network_interface_id }}
  when: _aws_ec2_eni_facts.network_interfaces | length == 1

- block:

    - name: create network interface
      ec2_eni:
        private_ip_address: '{{ _aws_ec2_i["private_ip"] | default(omit) }}'
        profile: '{{ aws_profile }}'
        region: '{{ aws_region }}'
        security_groups: '{{ _aws_ec2_i["group"] }}'
        subnet_id: '{{ _aws_ec2_subnet }}'
      register: _aws_ec2_eni_create

    - name: set network interface ID fact
      set_fact:
        _aws_ec2_eni_id: '{{ _aws_ec2_eni_create.interface.id }}'

    - name: tag network interface
      ec2_tag:
        profile: '{{ aws_profile }}'
        region: '{{ aws_region }}'
        resource: '{{ _aws_ec2_eni_id }}'
        tags:
          Name: '{{ _aws_ec2_i["function"] }}'
          Environment: '{{ _aws_ec2_i["environment"] }}'
          VPC: '{{ aws_vpc_name }}'

  when: _aws_ec2_eni_facts.network_interfaces | length == 0

- name: associate Elastic IP address with network interface
  ec2_eip:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    device_id: '{{ _aws_ec2_eni_id }}'
    in_vpc: yes
    public_ip: '{{ _aws_ec2_i["public_ip"] | default(omit) }}'
    region: '{{ aws_region }}'
  when: >
    ( _aws_ec2_i["assign_public_ip"] is defined and
      _aws_ec2_i["assign_public_ip"] ) or
    _aws_ec2_i["public_ip"] is defined
