---

- name: launch instance

  ec2:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    region: '{{ aws_region }}'

    key_name: '{{ _aws_ec2_i["key_name"] }}'
    instance_type: '{{ _aws_ec2_i["type"] }}'
    image: '{{ _aws_ec2_ami["image_id"] }}'

    wait: True

    instance_profile_name: '{{ _aws_ec2_i["profile"] | default(omit) }}'

    user_data: '{{ _aws_ec2_user_data | default(omit) }}'

    instance_tags: '{{ _aws_ec2_all_instance_tags }}'
    count_tag: '{{ aws_ec2_standard_instance_tags }}'
    exact_count:   1

    vpc_subnet_id:     '{{ vpc_subnet_id     | default(omit) }}'
    group:             '{{ group             | default(omit) }}'
    assign_public_ip:  '{{ assign_public_ip  | default(omit) }}'
    private_ip:        '{{ private_ip        | default(omit) }}'
    source_dest_check: '{{ source_dest_check | default(omit) }}'

    network_interface: '{{ network_interface | default(omit) }}'

    volumes: '{{ _aws_ec2_i["volumes"] }}'

  register: _aws_ec2_ec2

- name: save results if an EC2 launch occurred
  set_fact:
    _aws_ec2_launch: '{{ _aws_ec2_ec2 }}'
  when: _aws_ec2_ec2.changed
