---

- name: clear aws_ec2_instances from earlier includes
  set_fact:
    aws_ec2_instances: []

- name: read variables for EC2 instance function
  include_vars: '{{ _aws_ec2_function_file }}'

- name: add instance to target list if it is in a target environment
  set_fact:
    _aws_ec2_target_instances: >-
      {{ _aws_ec2_target_instances
         | default([])
         | union([instance]) }}
  with_items: '{{ aws_ec2_instances }}'
  when: >
    ( instance.function in _aws_ec2_target_functions or
      _aws_ec2_target_functions == [""] ) and
    ( instance.environment in _aws_ec2_target_environments or
      _aws_ec2_target_environments == [""] )
  loop_control:
    loop_var: instance
