---

- name: read variables for EC2 instance function
  include_vars: '{{ _aws_ec2_function_file }}'

- name: add instance to those to be configured if it is in a named environment
  set_fact:
    _aws_ec2_all_instances: >-
      {{ _aws_ec2_all_instances
         | default([])
         | union([instance]) }}
  with_items: '{{ aws_ec2_instances }}'
  when: >
    ( instance.function in _aws_ec2_functions or
      _aws_ec2_functions == [""] ) and
    ( instance.environment in _aws_ec2_environments or
      _aws_ec2_environments == [""] )
  loop_control:
    loop_var: instance
