---

- name: retrieve AMI facts
  ec2_ami_find:
    ami_id: '{{ _aws_ec2_i["image"] | default(aws_ec2_instance_defaults["image"]) }}'
    profile: '{{ aws_profile }}'
    region: '{{ aws_region }}'
  register: _aws_ec2_ami_facts

- name: construct instance user data
  set_fact:
    _aws_ec2_user_data:
      '{{ lookup("template",
                 playbook_dir
                 + "/roles/aws-ec2/templates/user_data/"
                 + (_aws_ec2_ami_facts.results[0].platform or "linux")
                 + ".j2") }}'
