---

- name: construct instance user data
  set_fact:
    _aws_ec2_user_data:
      '{{ _aws_ec2_i["user_data"]
          | default(lookup("template",
                           playbook_dir
                           + "/roles/aws-ec2/templates/user_data/"
                           + (_aws_ec2_ami["platform"] | default("linux"))
                           + ".j2")) }}'
